### ISSUE TITLE
Top level search page is needed

### ISSUE THREAD

**Issue by Altai-man** [Altai-man/docs.raku.org#14]
This is a big and interesting ticket.
There is a long term demand (https://github.com/Raku/doc/issues/1099) for serving a dynamic page for search.

It can be either JS-based or backend based, but looking at various options I myself did not really find anything that seems okay-ish enough just as JS we use now.

Right now, we serve such a static page:

![2020-12-05-183401_1920x1080_scrot](https://user-images.githubusercontent.com/5764435/101258175-57bb1f80-3729-11eb-8bc2-b4a1162cf81a.png)

We need pieces of JS to handle everything on it. This includes:

- [x] On typing in the search field we should query our JS search data and display formed results according to the layout in the UI mock-up.
- [x] Results counter is at the top right, it should be updated.
- [x] It has to be able to know about specific category chosen at the top left select and filter out results.
- [x] If the page is opened with `q=fofofo` query parameter, JS has to understand this, pre-fill the input with `fofofo` and display results for that, so that we could point this template to other search engines.

What is interesting here is that we want to avoid duplicating lots of code from search.js we have now (it will be inevitable anyway, but let's try to make the code structure as organized as possible).

**Comment by Altai-man** [comment]
@MorayJ hey, how are you doing?

**Comment by MorayJ** [comment]
Hi, ok. Little progress as have had a few things on my plate. But hoping to have a proper go during the rest of this week...

**Comment by MorayJ** [comment]
Hit a blocker...docker image build is too big for my virtual machine which is set up for doing this and getting this error on the familiar way of running it:

Error running DOCKY_PORT=20000 DOCKY_HOST=localhost raku -Ilib service.p6 #32

**Comment by Altai-man** [comment]
I decided to make the burden less heavy for everyone and help with the code. My current code is:

```
$(function(){
    // What we need to do is:
    // 1)process initial query we might have in URL parameters
    // 2)Setup an input callback
    var urlParams = new URLSearchParams(window.location.search);
    var queryParam = urlParams.get('q');
    if (queryParam !== null) {
        $("#search-input").val(queryParam);
        processQuery(queryParam);
    }

    $("#search-input").keyup(function() { processQuery($("#search-input").val()); });
});

function processQuery(value) {
    if (value.length == 0) {
        return;
    }

    var res = fuzzysort.go(value, items, {
        limit: 5, // Don't return more results than this (lower is faster)
        allowTypo: true,
        key: 'value'
    });
    $("#search-count").text("Found: " + res.length);

    var resultsLen = res.length;
    var resultsCategorized = new Map();

    for (var i = 0; i < resultsLen; i++) {
        var item = res[i].obj;
        if (resultsCategorized.has(item.category)) {
            resultsCategorized.get(item.category).push(item);
        } else {
            resultsCategorized.set(item.category, []);
            resultsCategorized.get(item.category).push(item);
        }
    }
    $('.results').empty();
    resultsCategorized.forEach(function(value, key) {
        var catBox = $('<div/>')
            .addClass("box search-category")
            .append($('<div/>').addClass("search-category-title has-text-centered subtitle")
            .text(key));
        for (var i = 0; i < value.length; i++) {
            catBox.append(
                $('<article/>')
                    .addClass("search-item")
                    .append($('<div/>').addClass("search-item-title")
                        .append($('<a/>').attr("href", value[i].url).text(value[i].value)))
                    .append($('<p/>').text('Placerat orci <span class="search-match">nulla pellentesque</span> dignissim enim, sit amet venenatis urna cursus eget? Neque ornare aenean euismod elementum nisi, quis eleifend quam adipiscing vitae proin sagittis, nisl rhoncus mattis rhoncus, urna!'))
            );
        }
        $('.results').append(catBox);
    });
}
```

It is still incomplete (does not account for the category selection, but that's easy), plus I am wondering about a proper "description" of the results... This probably wants some backend help, but other than that it does everything that's needed. Suggestions are welcome.
