### ISSUE TITLE
Top navbar search should respect small screen layout

### ISSUE THREAD

**Issue by ogdenwebb** [Altai-man/docs.raku.org#16]
If you keep the style attribute (style="width: 200px;") within the navbar search field, it will break input size on small screens. 

**Scenario to reproduce**

1. Open browser inspector/devtools and choose 720p screen.
2. Use horizontal orientation.
3. Type something to search in navbar.
4. Deselect the search field and switch to vertical orientation in inspector/devtools.
5. Open a hamburger menu.

**Comment by 2colours** [comment]
Does this issue still persist? I failed to reproduce it with the given description but maybe I'm missing something.

**Comment by Altai-man** [comment]
It's an old one, let's close it and see if anyone else complains with fresher description.
