### ISSUE TITLE
License? 

### ISSUE THREAD

**Issue by codesections** [Altai-man/docs.raku.org#27]
Is this repo licensed under the same Artistic License 2.0 as Raku/other main Raku projects?  If so, I'd be happy to submit a PR adding the LICENSE and updating the META6.json – but I don't want to assume, since it's your project and you get to pick the license :grin:

**Comment by Altai-man** [comment]
I am not a lawyer and even TLDRLicense is not so helping much, so it's a bit of a bother.
I don't mind using Artistic License 2.0.

**Comment by Altai-man** [comment]
https://github.com/Altai-man/docs.raku.org/commit/395f1255bba21fe079d4efe8ac928571f5fac789
