### ISSUE TITLE
Filter searching broken

### ISSUE THREAD

**Issue by MorayJ** [Altai-man/docs.raku.org#33]
Using symbols to select a specific catgory ((), &, .) in the search field isn't working as expected.

**Comment by Altai-man** [comment]
Are you using my documentation fork with straightened search categories?

**Comment by MorayJ** [comment]
No. What should I be using?

**Comment by Altai-man** [comment]
>git clone -b search-categories https://github.com/Raku/doc.git

^, you also need our fork of Documentable.

See https://github.com/Altai-man/docs.raku.org#manual-installation for updated instructions to check if you are missing anything.

**Comment by MorayJ** [comment]
Ok, I'm not getting this. I've gone to the link and started again in a fresh directory. There is no `service.p6` in either the doc directory or the Documentalbe directory so the command:
`DOCKY_PORT=20000 DOCKY_HOST=localhost raku -Ilib service.p6`
fails

**Comment by Altai-man** [comment]
The `service.p6` script is in this repo. Everything happening in the manual installation is withing this repo clonned, so first you clone it and then do all the commands listed.

It is a sad misunderstanding, I will update the docs soon to make it clear from the beginning.

**Comment by Altai-man** [comment]
The report is about incorrect installation, as it works fine, so closing.
