### ISSUE TITLE
I get a SSL_ERROR_RX_RECORD_TOO_LONG randomly

### ISSUE THREAD

**Issue by CodeCanna** [Altai-man/docs.raku.org#39]
So I have been getting this error since using the site.  It usually doesn't appear right away, but after going to a few links on the page to other parts of the site.  I am using Firefox 87.0 with Pop_OS! latest.  I'm happy to provide more data if needed.

The only pattern I can discern is that if I start a fresh session or go to https://docs.raku.org/ directly I can get to a few pages before getting the error, and then to continue using the site I have to go to that link again directly.  But now however I am noticing that if I come directly to that link, sometimes I get what appears to be the CSS failing to load:
![image](https://user-images.githubusercontent.com/22159040/115946754-850e2d00-a480-11eb-95bd-9d410d784de6.png)

I'm also getting some JS errors:
![image](https://user-images.githubusercontent.com/22159040/115946797-ca325f00-a480-11eb-8b95-be1bb2acaf17.png)

And after refreshing I get:
![image](https://user-images.githubusercontent.com/22159040/115946816-f51cb300-a480-11eb-9d2c-b521ef8e87f3.png)

**Comment by Altai-man** [comment]
Is it so for you with the https://docs.raku.org/ website or where this actual website is temporarily hosted, at http://raku-infra-fsn1-01.rakulang.site:10012/ ? I guess the first one, so I am not of much help here.

**Comment by Altai-man** [comment]
The ticket doesn't relate to the actual website anymore, so closing. Please, re-open if needed.
