### ISSUE TITLE
left nav hides content

### ISSUE THREAD

**Issue by coke** [Altai-man/docs.raku.org#41]
When going to a new page, e.g.:

http://164.90.207.89:10010/programs/01-debugging

the left nav pops out, obscuring the content. It would be nice if when expanded, all content was still visible (or, if that's problematic, if the page started with the nav hidden)

**Comment by Altai-man** [comment]
What's your screen resolution?

**Comment by coke** [comment]
If I expand the window to about 1742 pixels, I can see all the content, but there is a HUGE whitespace border on the right of the content (bigger than the width of the left nav), and the content is JUST visible on the left.

**Comment by Altai-man** [comment]
Can you post a screenshot please?

**Comment by coke** [comment]
![docs](https://user-images.githubusercontent.com/50257/164081805-3d5bf201-4668-4c60-b495-9179ecdadd21.png)

This is the side nav visible, hiding the left gutter; any thinner, and the left nav obscures the content.

Sounds like you're saying works as intended. I'll test the state of the nav being remembered and open a separate ticket for that if needed.

**Comment by Altai-man** [comment]
>Sounds like you're saying works as intended. I'll test the state of the nav being remembered and open a separate ticket for that if needed.

Yup. I agree it's not ideal, but judging the pros and cons this was set as the best compromise solution.
The sidebar is less prominent when it works properly. And on the second thought, we can make it even smarter, hiding it if the screen resolution is too narrow.

Another good thing about such a layout is that on a small mobile screen you don't need to scroll all the way up if you want to see the table of content.

**Comment by Altai-man** [comment]
As https://github.com/Altai-man/docs.raku.org/issues/44 is closed, closing this too.

**Comment by Veraellyunjie** [comment]
Please reconsider this issue:

![left nav](https://user-images.githubusercontent.com/75799052/168693243-2f3e232a-8f41-4679-9170-444ce2445cb3.png)

> the left nav pops out, obscuring the content. It would be nice if when expanded, all content was still visible (or, if that's problematic, if the page started with the nav hidden)

Absolutely agree.
My resolution 1600x900.
Browsers surf-2.1 and Iridium 2022.04

Also please note color of snippets doesn't play nice with dark theme

**Comment by Altai-man** [comment]
>Also please note color of snippets doesn't play nice with dark theme

That's a valid bug, I agree.
