### ISSUE TITLE
Generated by links incorrect

### ISSUE THREAD

**Issue by coke** [Altai-man/docs.raku.org#42]
e.g.: http://164.90.207.89:10010/programs/01-debugging

link at the bottom points to:

http://164.90.207.89:10010/programs/%7B%7BpodPath%7D%7D

but should probably point to the pod6 file in github for raku/doc (bonus points for pointing to a branch if that's what was used)

**Comment by Altai-man** [comment]
Ugh, so it rotted. :)

Thanks for spotting.

**Comment by Altai-man** [comment]
Closed by https://github.com/Altai-man/docs.raku.org/commit/73bb36af5f43ed3081885a64155c5d5a1cc07bcd
