### ISSUE TITLE
Paragraphs are not rendered

### ISSUE THREAD

**Issue by patrickbkr** [Altai-man/docs.raku.org#43]
Paragraphs are not rendered. See e.g. http://164.90.207.89:10010/language/syntax vs https://docs.raku.org/language/syntax and https://github.com/Raku/doc/edit/master/doc/Language/syntax.pod6

**Comment by Altai-man** [comment]
Fixed with https://github.com/Altai-man/docs.raku.org/commit/b9d468e3c8a36b7bcad4d528937ac009d52ee787 and deployed.

Deploy tooling is rather basic, so expect more fixes be checked locally and deployed later "at once".
