### ISSUE TITLE
left nav state not remembered

### ISSUE THREAD

**Issue by coke** [Altai-man/docs.raku.org#44]
if I go to a page and hide the left nav, clicking on any other link in the doc site re-opens the left nav.

E.g.:

http://164.90.207.89:10010/routine-term

nav is open. hide it.

Click on "routines" at the top. left nav is open again.

Hide it. surf to http://164.90.207.89:10010/routine/now ; left nav is open again

**Comment by Altai-man** [comment]
Fixed by https://github.com/Altai-man/docs.raku.org/commit/b75a5b6e74278e6b9822cf047216846051d71c17
