### ISSUE TITLE
home page cards not clickable

### ISSUE THREAD

**Issue by coke** [Altai-man/docs.raku.org#45]
http://164.90.207.89:10010/

clicking on "Learn More" in any card takes me to the apppropriate section, but:

clicking on "Type Reference" does nothing.

I expect the text of the card and the icon to go to the same location as the learn more button.

**Comment by Altai-man** [comment]
Closed by https://github.com/Altai-man/docs.raku.org/commit/16755101135966941ef644feecf55df3e6ecafea
