### ISSUE TITLE
Code quotes are badly readable when using the dark theme

### ISSUE THREAD

**Issue by patrickbkr** [Altai-man/docs.raku.org#53]
e.g. http://164.90.207.89:10010/language/quoting#index-entry-heredocs_:to-Heredocs:_:to
![image](https://user-images.githubusercontent.com/6307078/169702933-263bcc6f-eb89-4450-9fa5-50f7cc1f8d5e.png)

**Comment by Altai-man** [comment]
I believe it's closed with https://github.com/Altai-man/docs.raku.org/commit/53ead00803a59f1f8b991e90d04bd328d4562905
