### ISSUE TITLE
Search breaks when searching for "garbage-collection"

### ISSUE THREAD

**Issue by patrickbkr** [Altai-man/docs.raku.org#54]
With breaking I mean that the dropdown doesn't appear and when pressing enter the letters that were there when the dropdown worked for the last time is searched, not the current word.

"garba" works
"garbag" doesn't work, searches for "garba"
"garbage" works
"garbage-" doesn't work, searches for "garbage"
"garbage-c" and anything longer doesn't work, searches for "garbage"

**Comment by patrickbkr** [comment]
The issue is not about the search word being found, but about the dropdown not appearing and the google search not searching for the word currently typed in. "garbage-collection" was just the example.

**Comment by Altai-man** [comment]
I see, thanks.

**Comment by Altai-man** [comment]
Worked out how it happens, need a bit more of a UI help and it'll be resolved.
