### ISSUE TITLE
TOC hover-over can be confusing on mobile

### ISSUE THREAD

**Issue by patrickbkr** [Altai-man/docs.raku.org#55]
![image](https://user-images.githubusercontent.com/6307078/169716533-a9878322-5ca8-4e06-bcbd-2f99617a239c.png)
On mobile the TOC can overlap the content. I sometimes are confused for a bit by the result. In the above case wondering, why the operator precedence table contains only examples.

My spontaneous idea would be to hide the TOC by default when it would overlap the content.

**Comment by Altai-man** [comment]
Fixed by https://github.com/Altai-man/docs.raku.org/commit/15e925e8176e2b3d2227ac59451eb2d39fd2092d
