### ISSUE TITLE
Search links to wrong anchor with `$*SCHEDULER`

### ISSUE THREAD

**Issue by patrickbkr** [Altai-man/docs.raku.org#56]
Searching for "scheduler" and then clicking on "$*SCHEDULER" leads to http://164.90.207.89:10010/language/variables#index-entry-$*SCHEDULER But that anchor doesn't exist. http://164.90.207.89:10010/language/variables#$*SCHEDULER exists though.

**Comment by Altai-man** [comment]
It boils down to https://gist.github.com/Altai-man/c15e580480d44616eace320ccda95ed3
Alas no feedback for the document so far.

**Comment by patrickbkr** [comment]
I left a comment.

**Comment by Altai-man** [comment]
So after 1 weekend of "no, I won't do it" denial and a weekend of acceptance, this one is... fixed.

With https://github.com/Raku/Pod-To-HTML/commit/813ef63bf8c3c48df55e87f24053e542edab5b28 and https://github.com/Raku/Documentable/commit/00c443272874504263102088f778673b338d670c we also got proper escaping of the URL fragments, which means all the non-standard URL fragments we had prior to this are broken, but I guess even if you walked 1000 miles into wrong direction you still have to go back and start to use percentage encoding for URLs.

Doing the build to upload the fix.
