### ISSUE TITLE
Document how to update doc repo

### ISSUE THREAD

**Issue by coke** [Altai-man/docs.raku.org#59]
We have docker instructions for doing the initial build of the site - because this takes a while, we probably need instructions on how to do the minimum to update the docs site; I'm guessing we also want those instructions to end with swapping out the old running site for the newly updated container, but I'm not 100% sure.

**Comment by Altai-man** [comment]
Can you please elaborate, do you mean loading a new version of the doc repo while the site is still running, replacing or in the future completing the existing content, or?

**Comment by coke** [comment]
I mean a new version of the doc repo on an already running instance of the website.

Once we're deployed and running on docs.raku.org, this will be a common use case.

**Comment by Altai-man** [comment]
That's something to implement, yes.

**Comment by Altai-man** [comment]
Wrote a prototype locally, need time to cleanup the code.

Right now the basic API is "get the git describe" of the doc repo used and an "update" command sent with a secret token, doing the "update the repo, registry and remove cache of the changed pages". So to update the version to latest what's needed is a ping to `docs.raku.org/update?token=...` and it does the thing.

Can be also configured to do an update every hour/day or something.

@coke does the process looks sensible to you in a long time?

**Comment by coke** [comment]
I don't like making this a public interface as it could be invoked by anyone and lead to a DDOS.

**Comment by Altai-man** [comment]
The update action is protected with a secret token (no token = forbidden), so it can lead to a DDOS as DDOS-ing every other page would, no?

**Comment by Altai-man** [comment]
Resolved, the docs are updated too.
