### ISSUE TITLE
Code snippets not displayed properly

### ISSUE THREAD

**Issue by uzluisf** [Altai-man/docs.raku.org#65]
Runnable code snippets without newlines and the contents is all jumbled up.

![image](https://user-images.githubusercontent.com/22332927/175838560-99e1737b-32bc-4183-b716-6d7213303aef.png)

**Comment by Altai-man** [comment]
Can you please provide some steps to reproduce?

**Comment by uzluisf** [comment]
Apologies for the late reply :sweat_smile:. The issue is fixed now (see image below). At the time I visited the [Classes and objects](http://164.90.207.89:10010/language/classtut) page but in hindsight, the issue might've been caused by my browser. 

![image](https://user-images.githubusercontent.com/22332927/178115596-09171220-3104-4645-b689-2546af3befc4.png)
