### ISSUE TITLE
Incomplete code snippets shouldn't have a "Run" button

### ISSUE THREAD

**Issue by uzluisf** [Altai-man/docs.raku.org#66]
This can be easily solved by adding the configuration info `:skip-test<incomplete code>` to the delimited block `=begin code`. However submitting an issue to call attention to it.

![image](https://user-images.githubusercontent.com/22332927/175838731-41420381-3793-47ec-8106-3fc6537bb2ed.png)

**Comment by Altai-man** [comment]
Are the marks already present in the current Pod for such examples?

**Comment by uzluisf** [comment]
Yeah, some code snippets already use the `:skip-test` flag/option (example [here](https://github.com/Raku/doc/blob/67b76cf5548150f45c3e7fa475d95a6acecb8186/doc/Language/classtut.pod6#L418)).

![image](https://user-images.githubusercontent.com/22332927/178115782-0a83d72f-9a37-487b-8cb1-a954447ed4ae.png)
![image](https://user-images.githubusercontent.com/22332927/178115784-1444950d-a98e-4ee1-a99f-eaf6d48f8b49.png)

The downside is that it does away with syntax highlighting.

**Comment by Altai-man** [comment]
Alright, thanks! I'll look at it.

**Comment by Altai-man** [comment]
Hmmm. I thought by chance I forgot to consider `skip-test` directive when deciding if the example is runnable, but no, it's there:

>my $lang = $node.config<lang> || $node.config<skip-test> ?? '' !! 'raku-lang';

Maybe the ticket is about "Error occurred" message, but the examples runner works now.

Can you please clarify what is the exact issue here? Absence of highlighting?

**Comment by uzluisf** [comment]
The issue I was alluding to is that incomplete pieces of code shouldn't have a "Run" button because 1) it signals that it should be runnable and 2) it will throw an error not necessarily related to the documentation around it. Take for example this under the [State](http://164.90.207.89:10010/language/classtut#State):

```raku
has &!callback;
```

If I run it, it throws the compiler-time error `You cannot declare attribute '&!callback' here;`. However if I'm new to Raku this might be confusing because I don't know if that's supposed to showcase something. For example, none of the text around it indicates that this is supposed to happen. Thus, what I'm getting at is that all incomplete code snippets should have that flag in order to avoid any confusion. I supposed it's only a matter of adding the flag to those code snippets but I wanted to raise the issue here first.

Hopefully this clears things up!
