### ISSUE TITLE
Code snippets are editable

### ISSUE THREAD

**Issue by patrickbkr** [Altai-man/docs.raku.org#71]
I just noticed, that it's possible to edit code snippets, even the ones that don't have a run button.
My proposal:

- Don't allow editing snippets that don't have a run button.
- Add a button to snippets that do have a run button to reset the snippet to its original text. Ideally such a "reset snippet" button would be inactive whenever the current text is identical to the original text.

I think this is somewhere in the middle between "bug report" and "wish list".

**Comment by Altai-man** [comment]
Closed, thanks to @2colours !
