### ISSUE TITLE
Sort each section’s item titles in alphabetical order

### ISSUE THREAD

**Issue by tbrowder** [Altai-man/docs.raku.org#72]

**Comment by Altai-man** [comment]
Hi! What sections do you mean?

**Comment by tbrowder** [comment]
For example, on the Language page, there are sections:

+ At the beginning
+ Migration guides
+ Tutorials
+ Fundamental topics
+ General reference
+ Advanced topicc

Each section has a list of subject titles and descriptions. For example, under the section **General reference** there are the following subjects:


| Subject | Description |
| ---  | --- |
| Terms | Raku terms |
| Glossary | Glossary of Raku terminology |
| ... | ... |

Notice the subject titles are unordered. They would be easier to peruse by ordering them alphabetically by subject so the example above would then look like this:

| Subject | Description |
| --- | --- |
| Glossary | Glossary ... |
| Terms | Raku terms |
| ... | ... |

**Comment by Altai-man** [comment]
I see, thanks! I'll look into it when time allows.

**Comment by 2colours** [comment]
Now that I have a working setup, I can also look into it. :) Maybe later today or this weekend.

**Comment by Altai-man** [comment]
It shouldn't be bad, most likely a map with sort around https://github.com/Altai-man/docs.raku.org/blob/master/lib/Docky/Routes/Index.pm6#L24-L25 will help.

**Comment by 2colours** [comment]
Actually, it seems to me that this is already fixed - the demo site hasn't been updated to the latest version.

**Comment by Altai-man** [comment]
>Actually, it seems to me that this is already fixed - the demo site hasn't been updated to the latest version.

The latest version was not uploaded, yes.

I find it hard to spend time on the website when it's in the limbo state as it is now, so try to do updates with more changes included at once.

**Comment by 2colours** [comment]
Yes, understandable... my personal motive is to contribute to something that is maintained to any extent, and might turn out to be useful. You probably know what "infinitely pending pull requests" are and you are doing just enough to avoid that situation. The rest is not directly up to us either way...
