### ISSUE TITLE
Inconsistent focus in search

### ISSUE THREAD

**Issue by 2colours** [Altai-man/docs.raku.org#79]
Let me demostrate the problem with merely a concrete example.

1. I type `put` in the search bar
![image](https://user-images.githubusercontent.com/37218286/199714136-4bf7b5e2-aff0-4ec9-9ba6-2bd6e93ffc63.png)
2. as can be seen, "Enter to select" shows up next to the routine - when enter is pressed, it's opened. The default position could be argued for and against, that's okay so far.
3. I hover other options and then move the cursor to a category (marked with the arrow)
![image](https://user-images.githubusercontent.com/37218286/199715622-30d35464-6c7c-4219-af39-69f21f83b2b4.png)
4. as can be seen, the focus returns to the default position - this is already quite disturbing
5. when pressing enter, the last hovered element will be opened, NOT the indicated (default) position

I would assume this is JS relevant. Trying to take a look at it myself later on.

**Comment by Altai-man** [comment]
I wouldn't assume it's a problem with focus, more so it's about some difference in expectations.

From my perspective, the user has two "modes": keyboard and keyboard+mouse.

If it's keyboard only, the "press enter" shortcut allows to quickly go there without mouse, if the result is not ambiguous. You can argue selecting answer row with arrows can be done (AFAIK it's not present...).

And if the user has to / wants to use mouse, they can as well just click on the item they want. It was never thought to be implemented as "enter will link to an item hovered" - why? I don't remember seeing it ever, it sounds like a very if not unexpected, then just "rare" UX decision.

Can you please elaborate on it?

**Comment by 2colours** [comment]
The problem is related to the comment of followLink() in search.js:

>     /* When using return key to select, the select event
>    and keydown event are both activated and the second
>    event should do nothing */

Indeed, the select event triggers in that case - and apparently even when we moved our cursor to a category name between the entries... that's why the wrong value is set before the redirection.

**Comment by 2colours** [comment]
Seems that the site is using an archaic and obscure jQuery UI plugin called "custom.catcomplete", probably for "category completion"... I'm afraid this needs to be completely rewritten in maintained jQuery at least.

**Comment by Altai-man** [comment]
If you have a better solution not involving this plugin with a rather cryptic interface, you'd be most welcome.

I also have an impression we might want to have a server-side search, but it's a lot more work to design it to actually be better than what we have now.
